name: Flake8
on:
  push:
    paths:
      - '**.py'
    branches:
      - main
  pull_request:
    paths:
      - '**.py'
    branches:
      - main

jobs:
  analyze:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: Set up latest stable Python version
      uses: actions/setup-python@v4
      with:
        python-version: '3.x'
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        python -m pip install flake8
        pip install -r requirements.txt
    - name: Lint package source with flake8
      run: |
        # stop the build if there are Python syntax errors or undefined names
        flake8 cs/aws_account --count --max-line-length=127 --select=E9,F63,F7,F82 --show-source --statistics
        # stop the build on all linting errors
        flake8 cs/aws_account --count --max-line-length=127 --statistics
