name: Check Docstrings
on:
  push:
    paths:
      - '**.py'
    branches:
      - main
  pull_request:
    paths:
      - '**.py'
    branches:
      - main

jobs:
  analyze:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v4
      with:
        python-version: ${{ matrix.python-version }}
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        python -m pip install pydocstyle
        pip install -r requirements.txt
    - name: Check package docstrings with pydocstyle
      run: |
        # Check docstring syntax
        pydocstyle cs/aws_account --count
