name: Check Docstrings
on:
  push:
    paths:
      - '**.py'
    branches:
      - main
  pull_request:
    paths:
      - '**.py'
    branches:
      - main

jobs:
  analyze:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: Set up latest stable Python version
      uses: actions/setup-python@v4
      with:
        python-version: '3.x'
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        python -m pip install pydocstyle
        pip install -r requirements.txt
    - name: Check package docstrings with pydocstyle
      run: |
        # Check docstring syntax
        pydocstyle cs/aws_account --count
